-- MySQL Script generated by MySQL Workbench
-- Mon Apr 29 19:44:22 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema TEST_dieta_v0
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema TEST_dieta_v0
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TEST_dieta_v0` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `TEST_dieta_v0` ;

-- -----------------------------------------------------
-- Table `TEST_dieta_v0`.`SequelizeMeta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TEST_dieta_v0`.`SequelizeMeta` (
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`name`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `TEST_dieta_v0`.`bowels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TEST_dieta_v0`.`bowels` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `consistency` INT(11) NULL DEFAULT NULL,
  `difficulty` INT(11) NULL DEFAULT NULL,
  `pain` INT(11) NULL DEFAULT NULL,
  `smell` INT(11) NULL DEFAULT NULL,
  `completeness` INT(11) NULL DEFAULT NULL,
  `urgency` INT(11) NULL DEFAULT NULL,
  `duration` INT(11) NOT NULL DEFAULT '0',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `TEST_dieta_v0`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TEST_dieta_v0`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `key` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 38
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `TEST_dieta_v0`.`exercise_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TEST_dieta_v0`.`exercise_types` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `creator_id` INT(11) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  `migration_id` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `exercise_types_name_creator_id` (`name` ASC, `creator_id` ASC) VISIBLE,
  INDEX `creator_id` (`creator_id` ASC) VISIBLE,
  CONSTRAINT `exercise_types_ibfk_1`
    FOREIGN KEY (`creator_id`)
    REFERENCES `TEST_dieta_v0`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `TEST_dieta_v0`.`exercises`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TEST_dieta_v0`.`exercises` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `intensity` INT(11) NULL DEFAULT NULL,
  `duration` INT(11) NOT NULL DEFAULT '0',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `TEST_dieta_v0`.`exercise_types_lists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TEST_dieta_v0`.`exercise_types_lists` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `exercise_id` INT(11) NOT NULL,
  `exercise_type_id` INT(11) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `exercise_types_lists_exercise_id_exercise_type_id` (`exercise_id` ASC, `exercise_type_id` ASC) VISIBLE,
  INDEX `exercise_type_id` (`exercise_type_id` ASC) VISIBLE,
  CONSTRAINT `exercise_types_lists_ibfk_1`
    FOREIGN KEY (`exercise_id`)
    REFERENCES `TEST_dieta_v0`.`exercises` (`id`),
  CONSTRAINT `exercise_types_lists_ibfk_2`
    FOREIGN KEY (`exercise_type_id`)
    REFERENCES `TEST_dieta_v0`.`exercise_types` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `TEST_dieta_v0`.`meal_ingredients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TEST_dieta_v0`.`meal_ingredients` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `creator_id` INT(11) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  `migration_id` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `meal_ingredients_name_creator_id` (`name` ASC, `creator_id` ASC) VISIBLE,
  INDEX `creator_id` (`creator_id` ASC) VISIBLE,
  CONSTRAINT `meal_ingredients_ibfk_1`
    FOREIGN KEY (`creator_id`)
    REFERENCES `TEST_dieta_v0`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `TEST_dieta_v0`.`meal_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TEST_dieta_v0`.`meal_items` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `creator_id` INT(11) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  `migration_id` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `creator_id` (`creator_id` ASC) VISIBLE,
  CONSTRAINT `meal_items_ibfk_1`
    FOREIGN KEY (`creator_id`)
    REFERENCES `TEST_dieta_v0`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `TEST_dieta_v0`.`meal_items_ingredients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TEST_dieta_v0`.`meal_items_ingredients` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `meal_item_id` INT(11) NOT NULL,
  `meal_ingredient_id` INT(11) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `meal_items_ingredients_meal_item_id_meal_ingredient_id` (`meal_item_id` ASC, `meal_ingredient_id` ASC) VISIBLE,
  INDEX `meal_ingredient_id` (`meal_ingredient_id` ASC) VISIBLE,
  CONSTRAINT `meal_items_ingredients_ibfk_1`
    FOREIGN KEY (`meal_item_id`)
    REFERENCES `TEST_dieta_v0`.`meal_items` (`id`),
  CONSTRAINT `meal_items_ingredients_ibfk_2`
    FOREIGN KEY (`meal_ingredient_id`)
    REFERENCES `TEST_dieta_v0`.`meal_ingredients` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `TEST_dieta_v0`.`meals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TEST_dieta_v0`.`meals` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(256) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `TEST_dieta_v0`.`meal_items_lists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TEST_dieta_v0`.`meal_items_lists` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `meal_id` INT(11) NOT NULL,
  `meal_item_id` INT(11) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `meal_items_lists_meal_id_meal_item_id` (`meal_id` ASC, `meal_item_id` ASC) VISIBLE,
  INDEX `meal_item_id` (`meal_item_id` ASC) VISIBLE,
  CONSTRAINT `meal_items_lists_ibfk_1`
    FOREIGN KEY (`meal_id`)
    REFERENCES `TEST_dieta_v0`.`meals` (`id`),
  CONSTRAINT `meal_items_lists_ibfk_2`
    FOREIGN KEY (`meal_item_id`)
    REFERENCES `TEST_dieta_v0`.`meal_items` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `TEST_dieta_v0`.`medication_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TEST_dieta_v0`.`medication_types` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `creator_id` INT(11) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  `migration_id` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `medication_types_name_creator_id` (`name` ASC, `creator_id` ASC) VISIBLE,
  INDEX `creator_id` (`creator_id` ASC) VISIBLE,
  CONSTRAINT `medication_types_ibfk_1`
    FOREIGN KEY (`creator_id`)
    REFERENCES `TEST_dieta_v0`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `TEST_dieta_v0`.`medications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TEST_dieta_v0`.`medications` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `TEST_dieta_v0`.`medication_types_lists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TEST_dieta_v0`.`medication_types_lists` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `medication_id` INT(11) NOT NULL,
  `medication_type_id` INT(11) NOT NULL,
  `quantity_num` FLOAT(11,6) NULL DEFAULT NULL,
  `quantity_unit` ENUM('mL', 'mg', 'g', 'pill(s)', 'capsule(s)') NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `medication_types_lists_medication_id_medication_type_id` (`medication_id` ASC, `medication_type_id` ASC) VISIBLE,
  INDEX `medication_type_id` (`medication_type_id` ASC) VISIBLE,
  CONSTRAINT `medication_types_lists_ibfk_1`
    FOREIGN KEY (`medication_id`)
    REFERENCES `TEST_dieta_v0`.`medications` (`id`),
  CONSTRAINT `medication_types_lists_ibfk_2`
    FOREIGN KEY (`medication_type_id`)
    REFERENCES `TEST_dieta_v0`.`medication_types` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `TEST_dieta_v0`.`mood_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TEST_dieta_v0`.`mood_types` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `creator_id` INT(11) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  `migration_id` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `mood_types_name_creator_id` (`name` ASC, `creator_id` ASC) VISIBLE,
  INDEX `creator_id` (`creator_id` ASC) VISIBLE,
  CONSTRAINT `mood_types_ibfk_1`
    FOREIGN KEY (`creator_id`)
    REFERENCES `TEST_dieta_v0`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `TEST_dieta_v0`.`moods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TEST_dieta_v0`.`moods` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `intensity` INT(11) NULL DEFAULT NULL,
  `duration` INT(11) NOT NULL DEFAULT '0',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `TEST_dieta_v0`.`mood_types_lists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TEST_dieta_v0`.`mood_types_lists` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `mood_id` INT(11) NOT NULL,
  `mood_type_id` INT(11) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `mood_types_lists_mood_id_mood_type_id` (`mood_id` ASC, `mood_type_id` ASC) VISIBLE,
  INDEX `mood_type_id` (`mood_type_id` ASC) VISIBLE,
  CONSTRAINT `mood_types_lists_ibfk_1`
    FOREIGN KEY (`mood_id`)
    REFERENCES `TEST_dieta_v0`.`moods` (`id`),
  CONSTRAINT `mood_types_lists_ibfk_2`
    FOREIGN KEY (`mood_type_id`)
    REFERENCES `TEST_dieta_v0`.`mood_types` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `TEST_dieta_v0`.`other_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TEST_dieta_v0`.`other_types` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `creator_id` INT(11) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  `migration_id` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `other_types_name_creator_id` (`name` ASC, `creator_id` ASC) VISIBLE,
  INDEX `creator_id` (`creator_id` ASC) VISIBLE,
  CONSTRAINT `other_types_ibfk_1`
    FOREIGN KEY (`creator_id`)
    REFERENCES `TEST_dieta_v0`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `TEST_dieta_v0`.`others`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TEST_dieta_v0`.`others` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `TEST_dieta_v0`.`other_types_lists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TEST_dieta_v0`.`other_types_lists` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `other_id` INT(11) NOT NULL,
  `other_type_id` INT(11) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `other_types_lists_other_id_other_type_id` (`other_id` ASC, `other_type_id` ASC) VISIBLE,
  INDEX `other_type_id` (`other_type_id` ASC) VISIBLE,
  CONSTRAINT `other_types_lists_ibfk_1`
    FOREIGN KEY (`other_id`)
    REFERENCES `TEST_dieta_v0`.`others` (`id`),
  CONSTRAINT `other_types_lists_ibfk_2`
    FOREIGN KEY (`other_type_id`)
    REFERENCES `TEST_dieta_v0`.`other_types` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `TEST_dieta_v0`.`sleeps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TEST_dieta_v0`.`sleeps` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `quality` INT(11) NULL DEFAULT NULL,
  `duration` INT(11) NOT NULL DEFAULT '0',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `TEST_dieta_v0`.`symptom_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TEST_dieta_v0`.`symptom_types` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `creator_id` INT(11) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  `migration_id` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `symptom_types_name_creator_id` (`name` ASC, `creator_id` ASC) VISIBLE,
  INDEX `creator_id` (`creator_id` ASC) VISIBLE,
  CONSTRAINT `symptom_types_ibfk_1`
    FOREIGN KEY (`creator_id`)
    REFERENCES `TEST_dieta_v0`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `TEST_dieta_v0`.`symptoms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TEST_dieta_v0`.`symptoms` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `duration` INT(11) NOT NULL DEFAULT '0',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `TEST_dieta_v0`.`symptom_types_lists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TEST_dieta_v0`.`symptom_types_lists` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `symptom_id` INT(11) NOT NULL,
  `symptom_type_id` INT(11) NOT NULL,
  `intensity` INT(11) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `symptom_types_lists_symptom_id_symptom_type_id` (`symptom_id` ASC, `symptom_type_id` ASC) VISIBLE,
  INDEX `symptom_type_id` (`symptom_type_id` ASC) VISIBLE,
  CONSTRAINT `symptom_types_lists_ibfk_1`
    FOREIGN KEY (`symptom_id`)
    REFERENCES `TEST_dieta_v0`.`symptoms` (`id`),
  CONSTRAINT `symptom_types_lists_ibfk_2`
    FOREIGN KEY (`symptom_type_id`)
    REFERENCES `TEST_dieta_v0`.`symptom_types` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `TEST_dieta_v0`.`user_bowels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TEST_dieta_v0`.`user_bowels` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `bowel_id` INT(11) NULL DEFAULT NULL,
  `notes` MEDIUMTEXT NULL DEFAULT NULL,
  `occurred_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  `uuid` CHAR(36) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid` (`uuid` ASC) VISIBLE,
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `bowel_id` (`bowel_id` ASC) VISIBLE,
  CONSTRAINT `user_bowels_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `TEST_dieta_v0`.`users` (`id`),
  CONSTRAINT `user_bowels_ibfk_2`
    FOREIGN KEY (`bowel_id`)
    REFERENCES `TEST_dieta_v0`.`bowels` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `TEST_dieta_v0`.`user_exercises`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TEST_dieta_v0`.`user_exercises` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `exercise_id` INT(11) NULL DEFAULT NULL,
  `notes` MEDIUMTEXT NULL DEFAULT NULL,
  `occurred_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  `uuid` CHAR(36) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid` (`uuid` ASC) VISIBLE,
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `exercise_id` (`exercise_id` ASC) VISIBLE,
  CONSTRAINT `user_exercises_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `TEST_dieta_v0`.`users` (`id`),
  CONSTRAINT `user_exercises_ibfk_2`
    FOREIGN KEY (`exercise_id`)
    REFERENCES `TEST_dieta_v0`.`exercises` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `TEST_dieta_v0`.`user_meals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TEST_dieta_v0`.`user_meals` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `meal_id` INT(11) NULL DEFAULT NULL,
  `notes` MEDIUMTEXT NULL DEFAULT NULL,
  `occurred_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  `uuid` CHAR(36) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid` (`uuid` ASC) VISIBLE,
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `meal_id` (`meal_id` ASC) VISIBLE,
  CONSTRAINT `user_meals_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `TEST_dieta_v0`.`users` (`id`),
  CONSTRAINT `user_meals_ibfk_2`
    FOREIGN KEY (`meal_id`)
    REFERENCES `TEST_dieta_v0`.`meals` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `TEST_dieta_v0`.`user_medications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TEST_dieta_v0`.`user_medications` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `medication_id` INT(11) NULL DEFAULT NULL,
  `notes` MEDIUMTEXT NULL DEFAULT NULL,
  `occurred_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  `uuid` CHAR(36) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid` (`uuid` ASC) VISIBLE,
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `medication_id` (`medication_id` ASC) VISIBLE,
  CONSTRAINT `user_medications_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `TEST_dieta_v0`.`users` (`id`),
  CONSTRAINT `user_medications_ibfk_2`
    FOREIGN KEY (`medication_id`)
    REFERENCES `TEST_dieta_v0`.`medications` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `TEST_dieta_v0`.`user_moods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TEST_dieta_v0`.`user_moods` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `mood_id` INT(11) NULL DEFAULT NULL,
  `notes` MEDIUMTEXT NULL DEFAULT NULL,
  `occurred_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  `uuid` CHAR(36) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid` (`uuid` ASC) VISIBLE,
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `mood_id` (`mood_id` ASC) VISIBLE,
  CONSTRAINT `user_moods_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `TEST_dieta_v0`.`users` (`id`),
  CONSTRAINT `user_moods_ibfk_2`
    FOREIGN KEY (`mood_id`)
    REFERENCES `TEST_dieta_v0`.`moods` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `TEST_dieta_v0`.`user_others`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TEST_dieta_v0`.`user_others` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `other_id` INT(11) NULL DEFAULT NULL,
  `notes` MEDIUMTEXT NULL DEFAULT NULL,
  `occurred_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  `uuid` CHAR(36) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid` (`uuid` ASC) VISIBLE,
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `other_id` (`other_id` ASC) VISIBLE,
  CONSTRAINT `user_others_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `TEST_dieta_v0`.`users` (`id`),
  CONSTRAINT `user_others_ibfk_2`
    FOREIGN KEY (`other_id`)
    REFERENCES `TEST_dieta_v0`.`others` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `TEST_dieta_v0`.`user_sleeps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TEST_dieta_v0`.`user_sleeps` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `sleep_id` INT(11) NULL DEFAULT NULL,
  `notes` MEDIUMTEXT NULL DEFAULT NULL,
  `occurred_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  `uuid` CHAR(36) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid` (`uuid` ASC) VISIBLE,
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `sleep_id` (`sleep_id` ASC) VISIBLE,
  CONSTRAINT `user_sleeps_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `TEST_dieta_v0`.`users` (`id`),
  CONSTRAINT `user_sleeps_ibfk_2`
    FOREIGN KEY (`sleep_id`)
    REFERENCES `TEST_dieta_v0`.`sleeps` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `TEST_dieta_v0`.`user_symptoms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TEST_dieta_v0`.`user_symptoms` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `symptom_id` INT(11) NULL DEFAULT NULL,
  `notes` MEDIUMTEXT NULL DEFAULT NULL,
  `occurred_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  `uuid` CHAR(36) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid` (`uuid` ASC) VISIBLE,
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `symptom_id` (`symptom_id` ASC) VISIBLE,
  CONSTRAINT `user_symptoms_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `TEST_dieta_v0`.`users` (`id`),
  CONSTRAINT `user_symptoms_ibfk_2`
    FOREIGN KEY (`symptom_id`)
    REFERENCES `TEST_dieta_v0`.`symptoms` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
